name: file_manager
description: FileManager is a wonderful widget that allows you to manage files
  and folders, pick files and folders, and do a lot more. Designed to feel like
  part of the Flutter framework.
version: 1.0.2
homepage: https://github.com/DevsOnFlutter
repository: https://github.com/DevsOnFlutter/file_manager
documentation: https://github.com/DevsOnFlutter/file_manager/blob/main/README.md
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.15
  path_provider_aurora:
    git:
      url: https://gitlab.com/omprussia/flutter/flutter-plugins.git
      ref: path_provider_aurora-0.0.1
      path: packages/path_provider/path_provider_aurora


dev_dependencies:
  flutter_test:
    sdk: flutter
